version: '3'

services:
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - ./data/minio:/data
        command: server /data --address ":9004" --console-address ":9001"
        ports:
            - 9004:9004
            - 9001:9001

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc alias set myminio http://minio:9004 minio minio123;
            /usr/bin/mc mb myminio/somebucketname;
            /usr/bin/mc policy set public myminio/somebucketname;
            exit 0;
            "
