version: '3'

tasks:
    fixtures:
        desc: Generate fixtures for dev environment
        cmds:
            - symfony console d:d:d --force --if-exists --quiet
            - symfony console d:d:c --quiet
            - symfony console d:s:u --force --quiet
            - symfony console d:m:sync-metadata-storage --quiet
            - symfony console d:m:v --add --all --quiet
            - symfony console a:f:l --quiet

    composer:
        desc: Install PHP vendors
        cmds:
            - symfony composer install
        sources:
            - composer.lock
        generates:
            - vendor/**/*

    start:
        desc: Start Symfony server
        cmds:
            - symfony serve -d

    stop:
        desc: Stop Symfony server
        cmds:
            - symfony server:stop

    docker-start:
        desc: Start Docker images
        cmds:
            - docker-compose up -d

    docker-stop:
        desc: Stop Docker images
        cmds:
            - docker-compose stop

    test:
        desc: Run tests
        cmds:
            - task: setup_tests
            - symfony php vendor/bin/phpunit
            - task: cleanup_tests

    coverage:
        desc: Run tests with coverage
        cmds:
            - task: setup_tests
            - symfony php -dpcov.enabled=1 vendor/bin/phpunit --coverage-html=public/coverage
            - task: cleanup_tests

    setup_tests:
        cmds:
            - docker-compose -f docker-compose.test.yaml up -d
            - rm -rf var/cache/test/*
            - symfony console d:d:d --force --if-exists --quiet --env=test
            - symfony console d:d:c --quiet --env=test
            - symfony console d:s:u --force --quiet --env=test
            - symfony console a:f:l --quiet --env=test

    cleanup_tests:
        cmds:
            - docker-compose -f docker-compose.test.yaml stop
            - docker-compose -f docker-compose.test.yaml down

    ci:
        desc: Check code style, static analysis...
        cmds:
            - symfony composer ci

    cs-fix:
        desc: Fix code style
        cmds:
            - symfony composer cs:fix

    install:
        desc: Install project
        cmds:
            - task: composer
            - symfony console app:post-install
            - symfony console app:regenerate-app-secret
            - symfony console doctrine:database:create
            - symfony console doctrine:migrations:migrate --no-interaction
            - symfony console app:make-user

    update:
        desc: Update project
        cmds:
            - git pull --rebase
            - task: composer
            - symfony console doctrine:migrations:migrate --no-interaction
            - symfony console app:post-install --only-missing
